### ISSUE TITLE
Team Size not specified on Skirm or Tournament

### ISSUE THREAD

**Issue by SkirmishPro** [KyleKaniecki/Skirmish-Issues#37]
**Bug Subsystem**: 
Skirms and Tournaments

**Expected Behavior:** 
As user I should be able to see the team size requirement for a Skirm or Tournament.

**Actual Behavior:** 
I'm unable to tell how many players I need on my team to play in a Team Skirm or Tournament.

**Reproduction Steps**: 
N/A

**Screenshots:** 
N/A

**Additional Information:** 
It may clutter the listings page but I think we should be as upfront as possible. Try to display the team size on the listing page and see how it looks. If it's "too much" then we should at least add it to the details page for both Skirms and Tournaments.

**Comment by KyleKaniecki** [comment]
Yeah, this could be a little much for the listings page. The problem isn't necessarily that it won't fit or is hard to add. The problem is when the **screen size** is too small. Then the columns get smashed together and look terrible. I will test it out on listing and details at first, then move to just details if it gets too cluttered.
